name: Check

on:
  pull_request:
    branches:
      - develop
      - main
      - "release/**"
  push:
    branches:
      - develop
      - main
      - "release/**"

jobs:
  run_check:
    name: Run Check
    runs-on: ubuntu-latest
    steps:
      - name: Echo status
        run: |
          echo "Status: Okay."
